[package]
name = "apk-fetch"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "apk_fetch"
path = "src/lib.rs"

[[bin]]
name = "apk-fetch"
path = "src/main.rs"

[dependencies]
contract.workspace = true
fetch.workspace = true
apkmirror.workspace = true
apkpure.workspace = true
apkcombo.workspace = true
uptodown.workspace = true
tokio.workspace = true
clap.workspace = true
anyhow.workspace = true
colored.workspace = true
indicatif.workspace = true
serde.workspace = true
serde_json.workspace = true
